<?php

namespace Fp\RubricaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComuneRepository extends \Doctrine\ORM\EntityRepository
{
}
