<?php

namespace Fp\RubricaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends EntityRepository
{
    public function findByCountryId($regione_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT province
            FROM RubricaBundle:Provincia provincia
            LEFT JOIN provincia.regione regione
            WHERE regione.id = :regione_id
        ")->setParameter('regione_id', $regione_id);

        return $query->getArrayResult();
    }
}