<?php

namespace Fp\RubricaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends EntityRepository
{
    public function findByCountryId($country_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT province
            FROM RubricaBundle:Province province
            LEFT JOIN province.country country
            WHERE country.id = :country_id
        ")->setParameter('country_id', $country_id);

        return $query->getArrayResult();
    }
}
