<?php

namespace Fp\RubricaBundle\Entity;

/**
 * RubricaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricaRepository extends \Doctrine\ORM\EntityRepository
{
 
}
