<?php

namespace Fp\RubricaBundle\Entity;

/**
 * UfficioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UfficioRepository extends \Doctrine\ORM\EntityRepository
{ 
}
