#services:
###    rubrica.example:
###        class: Fp\RubricaBundle
###        arguments: [@service_id, "plain_value", %parameter%]
#
#parameters:
#    my_mailer.transport:  sendmail
#     # Questo valore sarà analizzato come "@passwordsicura"
#    mailer_password: "@@passwordsicura"
#
#services:
#    my_mailer:
#        class:        Fp\RubricaBundle\Default
#        arguments:    ["%my_mailer.transport%"]
services:
    my.listener:
        class: Fp\RubricaBundle\EventListener\WriteTable
        tags:
            - { name: doctrine.event_listener, event: PreUpdate }
    
            
            
