security:    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
                use_referer: true
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      8e26a48da6fea97ecd89f4c0d2d86004
                lifetime: 360000000
                path:     /
                domain:   ~
            anonymous:  ~
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/*, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]
