<?php

namespace Fp\AnagraficaBundle\Entity;

/**
 * AnagraficaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnagraficaRepository extends \Doctrine\ORM\EntityRepository
{
}
