<?php

namespace AppBundle\Entity;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tasks2Repository extends \Doctrine\ORM\EntityRepository
{
}
