services:
    login_listener:
        class: Fp\UserBundle\Listener\LoginListener
        arguments: [@fos_user.user_manager, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method :onSecurityInteractiveLogin }
